fix crosspost hover
Microsoft-community/Windows-theme pull request #189
Opened 2017-10-17 14:33 UTC by corinneling

An external reddit css file was telling the crosspost image to be at a larger width that it should be when hovered, so I created a new css file "crosspost.css" in the css folder that should override that, and leave the other expando buttons untouched. for #188

2017-10-17 15:03 UTC, TheTimeWalker commented
Hey, thanks for trying to tackle the issue

Generally we work with SCSS files which allows us to have a single CSS file for the subreddit style. Your implementation won't work as Reddit doesn't allow you to have multiple CSS files. The only way your fix would work is when you implement this in a SCSS file like _core.scss and compile it to CSS with a SCSS tool

2017-10-17 15:44 UTC, corinneling commented
hi @TheTimeWalker, thanks for info. that is good to know! I have experience with sass and can implement that if it would help. If you'd like to take it or have someone else that's no problem 👍

2017-10-17 16:39 UTC, Jasius commented
Hey, just add it to _core.scss and it should be good to go(if it's working properly)

2017-10-17 17:27 UTC, quinn-joyce commented
k, I added it to the _core.scss file. It should work now. Thanks!

2017-10-17 20:04 UTC, Jasius commented
It does a slight jump whenever state changes, would be good if you adjusted it to this 

```
 .expando-button.collapsed.crosspost {
    width: 20px !important;
    &:hover {
         width: 20px !important;
 }
 }
```

So that the both states are at the same size and there's no jumping.

2017-10-17 20:12 UTC, Jasius requested changes
It does a slight jump whenever state changes, would be good if you adjusted it to this 

```
 .expando-button.collapsed.crosspost {
    width: 20px !important;
    &:hover {
         width: 20px !important;
 }
 }
```

So that the both states are at the same size and there's no jumping.

2017-10-21 21:23 UTC, Jasius commented
@corinneling any progress?

2017-10-23 14:01 UTC, corinneling commented
@Jasius, I added the requested code, thanks for checking in again 👍

2017-10-24 13:43 UTC, Jasius approved these changes

2017-10-24 13:43 UTC, Jasius commented
Thanks.

2017-10-24 13:43 UTC, merged